### ISSUE TITLE
Clarification of lineage and trait vectors

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/CAMPSITE#3]
Am I correct in interpreting that each trait vector relates to one of the lineage vectors?
https://github.com/annakrystalli/CAMPSITE/blob/560f8b5aa08820b16d73c22356d0524d606e9e28/R/sim_CAMPSITE.R#L44-L51

In which case I have a few questions:

- Just to confirm, the comparison will always on a single trait and be between two lineages, correct? Or do you want the code to be able to adjust to more comparisons?
- Is any information in the trait vector a reperition of information in an associated lineage vector? ie how does `status` value in trait vectors relate to `status` in lineage vectors?
- Also, just to confirm,  parental node (lineage number) in the lineage vector (first element) refers to the same property as parental lineage number (third element) in the trait vector does and therefore should have the same values across associated trait & lineage vectors? If so, why do both lineage vectors have the same parent_node: https://github.com/annakrystalli/CAMPSITE/blob/560f8b5aa08820b16d73c22356d0524d606e9e28/R/sim_CAMPSITE.R#L46-L47 whereas the parent node values in the trait vectors are different?

https://github.com/annakrystalli/CAMPSITE/blob/560f8b5aa08820b16d73c22356d0524d606e9e28/R/sim_CAMPSITE.R#L44-L45

**Comment by annakrystalli** [comment]
@alexsla

**Comment by annakrystalli** [comment]
BTW, I think after working more on the project I undestand what parental lineage is in the traits vectors (3rd element). I believe it's more like a relative id? If the trait is associated with an incipient lineage it refers to the parent id but if the trait is associated with a parental lineage, it is refers to the daughter id? Is this a correct interpretation?

**Comment by alexsla** [comment]
You're correct, each trait vector corresponds to each lineage vector.

So for each time step, the code first generates a matrix of all pairwise differences in traits. Then, for each lineage, it extracts the vector corresposing to that lineage (the difference between its trait and all others), and uses that trait of differences to calculate the effect of competition.
Yes, the status variable is replicated between the two, and yes you're correct that it's a relative id, based on whether it's an incipient or good lineage. I think I phrased it poorly in the annotation because I only wrote "parental lineage number (if incipient)" without adding what the value is if it's not an incipient lineage.
